name: vcard-personal-portfolio

components:
  - name: vcard-personal-portfolio
    type: docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production
    resources:
      cpu: 100m
      memory: 128Mi
